##################################################################
## Distributed under Creative Commons Atribution Licence (BY)
##  https://creativecommons.org/licenses/by/4.0/
## Author: Henryk Fukś, February 2026
##################################################################
## This program "experimentally" verifies correctness of 
## deterministic solution formulae
## for any of the 18 ternary CA rules induced by semigroups.
## Just change the number below ("rule=number"), the numbers 1..18
## are the same  as in the paper "Ternary cellular automata
## induced by semigroups of order 3 are solvable".
##################################################################
## The output consists of three pictures:
## (1) pattern generated by the CA rule by normal iterations;
## (2) the same pattern generated from the solution formula;
## (3) the difference between them (should be empty - all white).
#################################################################
  
import numpy as np 
import matplotlib.pyplot as plt 
from matplotlib.colors import ListedColormap
import math

############################################
#### ENTER RULE NUMBER 1..18 HERE ##########
rule=18
############################################

M=150#number of space sites
T=10 #number of iterations
 
x = [0]*M
# below we create initial condition, array of random integers
# p0 s probability of zero, p1 prob. of 1, p2 prob. of 2
p0=0.333333
p1=0.333333
p2=1-p0-p1
x = np.random.choice([0, 1, 2], size=M, p=[p0, p1, p2])

###############################################################
##########definitions of rules and solution functions##########

def f1(x0, x1, x2):
  return (x1+x2)%3

def Fsol1(i,n):
   return  sum(math.comb(n,j)*x[(i+j)%M] for j in range(0, n+1)) %3

def f2(x0, x1, x2):
  return 1+(x2**2-x2-1)*(x1**2-x1-1)

def Fsol2(i,n): 
   return  1+math.prod((x[(i+j)%M]**2-x[(i+j)%M]-1)**math.comb(n,j) for j in range(0, n+1))

def f3(x0, x1, x2):
  return 2*x1*(-2+x1)*x2*(-2+x2)
 
def Fsol3(i,n): 
   if n<2:
       return 2*x[i]*(-2+x[i])*x[(i+1)%M]*(-2+x[(i+1)%M]) 
   return  0

def f4(x0, x1, x2):
  return 1+(x2-1)*(x1-1)

def Fsol4(i,n): 
   return  1+math.prod((x[(i+j)%M]-1)**math.comb(n,j) for j in range(0, n+1))

def f5(x0, x1, x2):
  #return -x1**2*x2-x1*x2**2+x1**2+5*x1*x2+x2**2-3*x1-3*x2+2
  #return 1+(x2**2-3*x2+1)*(x1**2-3*x1+1)-x1*(2-x1)*x2*(2-x2)
  return 2-(-3+x1+x2)*(x1*x2-x1-x2)

def Fsol5(i,n): 
   return  1+math.prod((x[(i+j)%M]**2-3*x[(i+j)%M]+1)**math.comb(n,j) for j in range(0, n+1))\
       - math.prod(x[(i+j)%M] *(2-x[(i+j)%M]) for j in range(0,n+1))

def f6(x0, x1, x2):
  return 1+(x2**2-3*x2+1)*(x1**2-3*x1+1)

def Fsol6(i,n): 
   return  1+math.prod((x[(i+j)%M]**2-3*x[(i+j)%M]+1)**math.comb(n,j) for j in range(0, n+1))

def f7(x0, x1, x2):
  return 2       

def Fsol7(i,n): 
   return  2

def f8(x0, x1, x2):
  return x1*(-2+x1)*x2*(-2+x2)

def Fsol8(i,n): 
   return  math.prod(x[(i+j)%M]*(2-x[(i+j)%M]) for j in range(0, n+1))

def f9(x0, x1, x2):
  return (1/4)*x1*x2*(x2-3)*(x1-3)

def Fsol9(i,n): 
   return  math.prod((-1/2)*x[(i+j)%M]*(x[(i+j)%M]-3) for j in range(0, n+1))

def f10(x0, x1, x2):
  return -x1*x2*(x1*x2-x1-x2)

def Fsol10(i,n): 
   # commented is alternative version, also works
   #return  x[i]*math.prod(x[(i+j)%M]*(2-x[(i+j)%M]) for j in range(1, n+1)) +\
   #       x[(i+n)%M]*(x[(i+n)%M]-1)*math.prod(x[(i+j)%M]*(2-x[(i+j)%M]) for j in range(0, n)) 
   return  x[i]*x[(i+n)%M]*(x[i]+x[(i+n)%M]-x[i]*x[(i+n)%M]) *\
     math.prod(x[(i+j)%M]*(2-x[(i+j)%M]) for j in range(1, n))   
       
def f11(x0, x1, x2):
  return 1+(x1-1)**2          

def Fsol11(i,n): 
   return  1+(x[i]-1)**2

def f12(x0, x1, x2):
  return  -x1*x2*(-2+x1)

def Fsol12(i,n): 
   return  x[(i+n)%M]*math.prod(x[(i+j)%M]*(2-x[(i+j)%M]) for j in range(0, n))
       
def f13(x0, x1, x2):
  return max(x1,x2)

def Fsol13(i,n): 
   return  max(x[(i+j)%M] for j in range(0,n+1)) 

def f14(x0, x1, x2):
  return (1/2)*x1*x2*(3*x1*x2-5*x1-5*x2+9)

def Fsol14(i,n): 
   return math.prod(x[(i+j)%M]*(2-x[(i+j)%M]) for j in range(0,n+1))+\
       2*math.prod(x[(i+j)%M]*(x[(i+j)%M]-1)/2 for j in range(0,n+1))       
       
def f15(x0, x1, x2):
  return x1*(x1*x2**2-x1*x2-x2**2-2*x1+x2+4)/2       

def Fsol15(i,n):
    return x[i]*(2-x[i])+ 2*math.prod(x[(i+j)%M]*(x[(i+j)%M]-1)/2 for j in range(0,n+1))

def f16(x0, x1, x2):
  return 1+(x2-1)**2*(x1-1)

def Fsol16(i,n): 
   return  1+ (x[i]-1)*math.prod( (x[(i+j)%M]-1)**2 for j in range(1, n+1))

def f17(x0, x1, x2):
  return x1

def Fsol17(i,n): 
   return  x[i]

def f18(x0, x1, x2):
  return (1/2)*x1*(x1*x2-2*x1-x2+4)

def H(i,n): # needed for rule 18
# this works in python because it assumes math.prod(f(i) for i in range(0,0)) is 1
#    return x[(i+n)%M]*(2-x[(i+n)%M]) * math.prod(x[(i+j)%M]*(x[(i+j)%M]-1)/2 for j in range(0,n))  

# but this is mathematically more proper
     if n==0:
         return x[i]*(2-x[i])
     else:
         return x[(i+n)%M]*(2-x[(i+n)%M]) * math.prod(x[(i+j)%M]*(x[(i+j)%M]-1)/2 for j in range(0,n))  

def Fsol18(i,n):
    return sum(H(i,k) for k in range (0,n+1)) + \
        2*math.prod( x[(i+j)%M]*(x[(i+j)%M]-1)/2 for j in range(0,n+1))

###########################################################################

locfunctions = [f1,f2,f3,f4,f5,f6,f7,f8,f9,f10,f11,f12,f13,f14,f15,f16,f17,f18]  
solfunctions = [Fsol1,Fsol2,Fsol3,Fsol4,Fsol5,Fsol6,Fsol7,Fsol8,Fsol9,\
                Fsol10,Fsol11,Fsol12,Fsol13,Fsol14,Fsol15,Fsol16,Fsol17,Fsol18]


def f(rule, x0,x1,x2):
    return locfunctions[rule - 1](x0,x1,x2)

def Fsol(rule, i, n):
    return solfunctions[rule - 1](i,n)


# these are arrays where {0,1,2,..,T-1} is the range of first index (rows), 
# {0,1,2,..,M-1} is the range of the second index (columns)
# this construction guaranties that entries can be assigned independently
A = [[0 for _ in range(M)] for _ in range(T)] # actual iterations
B = [[0 for _ in range(M)] for _ in range(T)] # solution 
diffAB = [[0 for _ in range(M)] for _ in range(T)] # to store |A-B|

# iterate CA
for i in range(0,M):
    A[0][i]=x[i]
for t in range(0,T-1):
    for i in range(0,M):
        A[t+1][i]=f(rule,A[t][(i-1+M)%M], A[t][i], A[t][(i+1)%M])

# prepare solution array using solution formula
for i in range(0,M):
    B[0][i]=x[i]           
for t in range(1,T):
    for k in range(0,M):
        B[t][k]=Fsol(rule,k,t)

# compute difference between A and B
for t in range(1,T):
    for k in range(0,M):
        diffAB[t][k]=int(abs(A[t][k]-B[t][k]))

# color map white=0, green=1, blue=2
cmap = ListedColormap(['white', 'gray', 'blue'])
        
plt.imshow(A,cmap=cmap, vmin=0, vmax=2)
# uncomment if you want to save patterns in files
#filename = f"pattern{rule}.pdf"       
#plt.savefig(filename, format = 'pdf', dpi=300)
plt.show()
plt.imshow(B,cmap=cmap, vmin=0, vmax=2)
plt.show()
plt.imshow(diffAB,cmap=cmap, vmin=0, vmax=2) 
plt.show()
# check if all elements of diffAB are zero:
if not any(any(element != 0 for element in row) for row in diffAB):
    print("Both patterns match.")
else:
    print("Patterns do not match!")

# construct Wolfram number:
b0=f(rule,0,0,0)
b1=f(rule,0,0,1)
b2=f(rule,0,0,2)
b3=f(rule,0,1,0)
b4=f(rule,0,1,1)
b5=f(rule,0,1,2)
b6=f(rule,0,2,0)
b7=f(rule,0,2,1)
b8=f(rule,0,2,2)
gnumber=b0+ b1*3+ b2*9+ b3*27+ b4*81+ b5*243+ b6*729+ b7*2187+ b8*6561
print("Rule number as in the paper:", rule)
print("Wolfram rule number:",int(gnumber))
    
